# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:55:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AuthFailAction(Enum):
    AUTH_FAIL_ACTION_UNSPECIFIED = 'AUTH_FAIL_ACTION_UNSPECIFIED'
    AUTH_FAIL_ACTION_REDIRECT = 'AUTH_FAIL_ACTION_REDIRECT'
    AUTH_FAIL_ACTION_UNAUTHORIZED = 'AUTH_FAIL_ACTION_UNAUTHORIZED'


class Login(Enum):
    LOGIN_UNSPECIFIED = 'LOGIN_UNSPECIFIED'
    LOGIN_OPTIONAL = 'LOGIN_OPTIONAL'
    LOGIN_ADMIN = 'LOGIN_ADMIN'
    LOGIN_REQUIRED = 'LOGIN_REQUIRED'


class SecurityLevel(Enum):
    SECURE_UNSPECIFIED = 'SECURE_UNSPECIFIED'
    SECURE_DEFAULT = 'SECURE_DEFAULT'
    SECURE_NEVER = 'SECURE_NEVER'
    SECURE_OPTIONAL = 'SECURE_OPTIONAL'
    SECURE_ALWAYS = 'SECURE_ALWAYS'


class ApiConfigHandler(BaseModel):
    authFailAction: Optional[AuthFailAction] = Field(
        None,
        description='Action to take when users access resources that require authentication. Defaults to redirect.',
    )
    login: Optional[Login] = Field(
        None,
        description='Level of login required to access this resource. Defaults to optional.',
    )
    script: Optional[str] = Field(
        None, description='Path to the script from the application root directory.'
    )
    securityLevel: Optional[SecurityLevel] = Field(
        None, description='Security (HTTPS) enforcement for this URL.'
    )
    url: Optional[str] = Field(None, description='URL to serve the endpoint at.')


class ApiEndpointHandler(BaseModel):
    scriptPath: Optional[str] = Field(
        None, description='Path to the script from the application root directory.'
    )


class DatabaseType(Enum):
    DATABASE_TYPE_UNSPECIFIED = 'DATABASE_TYPE_UNSPECIFIED'
    CLOUD_DATASTORE = 'CLOUD_DATASTORE'
    CLOUD_FIRESTORE = 'CLOUD_FIRESTORE'
    CLOUD_DATASTORE_COMPATIBILITY = 'CLOUD_DATASTORE_COMPATIBILITY'


class ServingStatus(Enum):
    UNSPECIFIED = 'UNSPECIFIED'
    SERVING = 'SERVING'
    USER_DISABLED = 'USER_DISABLED'
    SYSTEM_DISABLED = 'SYSTEM_DISABLED'


class AuthorizedDomain(BaseModel):
    id: Optional[str] = Field(
        None,
        description='Fully qualified domain name of the domain authorized for use. Example: example.com.',
    )
    name: Optional[str] = Field(
        None,
        description='Full path to the AuthorizedDomain resource in the API. Example: apps/myapp/authorizedDomains/example.com.@OutputOnly',
    )


class BasicScaling(BaseModel):
    idleTimeout: Optional[str] = Field(
        None,
        description='Duration of time after the last request that an instance must wait before the instance is shut down.',
    )
    maxInstances: Optional[int] = Field(
        None, description='Maximum number of instances to create for this version.'
    )


class BuildInfo(BaseModel):
    cloudBuildId: Optional[str] = Field(
        None,
        description='The Google Cloud Build id. Example: "f966068f-08b2-42c8-bdfe-74137dff2bf9"',
    )


class CertificateRawData(BaseModel):
    privateKey: Optional[str] = Field(
        None,
        description='Unencrypted PEM encoded RSA private key. This field is set once on certificate creation and then encrypted. The key size must be 2048 bits or fewer. Must include the header and footer. Example: -----BEGIN RSA PRIVATE KEY----- -----END RSA PRIVATE KEY----- @InputOnly',
    )
    publicCertificate: Optional[str] = Field(
        None,
        description='PEM encoded x.509 public key certificate. This field is set once on certificate creation. Must include the header and footer. Example: -----BEGIN CERTIFICATE----- -----END CERTIFICATE----- ',
    )


class CloudBuildOptions(BaseModel):
    appYamlPath: Optional[str] = Field(
        None,
        description='Path to the yaml file used in deployment, used to determine runtime configuration details.Required for flexible environment builds.See https://cloud.google.com/appengine/docs/standard/python/config/appref for more details.',
    )
    cloudBuildTimeout: Optional[str] = Field(
        None,
        description='The Cloud Build timeout used as part of any dependent builds performed by version creation. Defaults to 10 minutes.',
    )


class ContainerInfo(BaseModel):
    image: Optional[str] = Field(
        None,
        description='URI to the hosted container image in Google Container Registry. The URI must be fully qualified and include a tag or digest. Examples: "gcr.io/my-project/image:tag" or "gcr.io/my-project/image@digest"',
    )


class CpuUtilization(BaseModel):
    aggregationWindowLength: Optional[str] = Field(
        None, description='Period of time over which CPU utilization is calculated.'
    )
    targetUtilization: Optional[float] = Field(
        None,
        description='Target CPU utilization ratio to maintain when scaling. Must be between 0 and 1.',
    )


class CreateVersionMetadataV1(BaseModel):
    cloudBuildId: Optional[str] = Field(
        None,
        description='The Cloud Build ID if one was created as part of the version create. @OutputOnly',
    )


class CreateVersionMetadataV1Alpha(BaseModel):
    cloudBuildId: Optional[str] = Field(
        None,
        description='The Cloud Build ID if one was created as part of the version create. @OutputOnly',
    )


class CreateVersionMetadataV1Beta(BaseModel):
    cloudBuildId: Optional[str] = Field(
        None,
        description='The Cloud Build ID if one was created as part of the version create. @OutputOnly',
    )


class CustomMetric(BaseModel):
    filter: Optional[str] = Field(
        None, description="Allows filtering on the metric's fields."
    )
    metricName: Optional[str] = Field(None, description='The name of the metric.')
    singleInstanceAssignment: Optional[float] = Field(
        None,
        description='May be used instead of target_utilization when an instance can handle a specific amount of work/resources and the metric value is equal to the current amount of work remaining. The autoscaler will try to keep the number of instances equal to the metric value divided by single_instance_assignment.',
    )
    targetType: Optional[str] = Field(
        None,
        description='The type of the metric. Must be a string representing a Stackdriver metric type e.g. GAGUE, DELTA_PER_SECOND, etc.',
    )
    targetUtilization: Optional[float] = Field(
        None, description='The target value for the metric.'
    )


class DebugInstanceRequest(BaseModel):
    sshKey: Optional[str] = Field(
        None,
        description='Public SSH key to add to the instance. Examples: [USERNAME]:ssh-rsa [KEY_VALUE] [USERNAME] [USERNAME]:ssh-rsa [KEY_VALUE] google-ssh {"userName":"[USERNAME]","expireOn":"[EXPIRE_TIME]"}For more information, see Adding and Removing SSH Keys (https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys).',
    )


class DiskUtilization(BaseModel):
    targetReadBytesPerSecond: Optional[int] = Field(
        None, description='Target bytes read per second.'
    )
    targetReadOpsPerSecond: Optional[int] = Field(
        None, description='Target ops read per seconds.'
    )
    targetWriteBytesPerSecond: Optional[int] = Field(
        None, description='Target bytes written per second.'
    )
    targetWriteOpsPerSecond: Optional[int] = Field(
        None, description='Target ops written per second.'
    )


class Empty(BaseModel):
    pass


class RolloutStrategy(Enum):
    UNSPECIFIED_ROLLOUT_STRATEGY = 'UNSPECIFIED_ROLLOUT_STRATEGY'
    FIXED = 'FIXED'
    MANAGED = 'MANAGED'


class EndpointsApiService(BaseModel):
    configId: Optional[str] = Field(
        None,
        description='Endpoints service configuration ID as specified by the Service Management API. For example "2016-09-19r1".By default, the rollout strategy for Endpoints is RolloutStrategy.FIXED. This means that Endpoints starts up with a particular configuration ID. When a new configuration is rolled out, Endpoints must be given the new configuration ID. The config_id field is used to give the configuration ID and is required in this case.Endpoints also has a rollout strategy called RolloutStrategy.MANAGED. When using this, Endpoints fetches the latest configuration and does not need the configuration ID. In this case, config_id must be omitted.',
    )
    disableTraceSampling: Optional[bool] = Field(
        None,
        description='Enable or disable trace sampling. By default, this is set to false for enabled.',
    )
    name: Optional[str] = Field(
        None,
        description='Endpoints service name which is the name of the "service" resource in the Service Management API. For example "myapi.endpoints.myproject.cloud.goog"',
    )
    rolloutStrategy: Optional[RolloutStrategy] = Field(
        None,
        description='Endpoints rollout strategy. If FIXED, config_id must be specified. If MANAGED, config_id must be omitted.',
    )


class Entrypoint(BaseModel):
    shell: Optional[str] = Field(
        None,
        description='The format should be a shell command that can be fed to bash -c.',
    )


class ErrorCode(Enum):
    ERROR_CODE_UNSPECIFIED = 'ERROR_CODE_UNSPECIFIED'
    ERROR_CODE_DEFAULT = 'ERROR_CODE_DEFAULT'
    ERROR_CODE_OVER_QUOTA = 'ERROR_CODE_OVER_QUOTA'
    ERROR_CODE_DOS_API_DENIAL = 'ERROR_CODE_DOS_API_DENIAL'
    ERROR_CODE_TIMEOUT = 'ERROR_CODE_TIMEOUT'


class ErrorHandler(BaseModel):
    errorCode: Optional[ErrorCode] = Field(
        None, description='Error condition this handler applies to.'
    )
    mimeType: Optional[str] = Field(
        None, description='MIME type of file. Defaults to text/html.'
    )
    staticFile: Optional[str] = Field(
        None, description='Static file content to be served for this error.'
    )


class FeatureSettings(BaseModel):
    splitHealthChecks: Optional[bool] = Field(
        None,
        description="Boolean value indicating if split health checks should be used instead of the legacy health checks. At an app.yaml level, this means defaulting to 'readiness_check' and 'liveness_check' values instead of 'health_check' ones. Once the legacy 'health_check' behavior is deprecated, and this value is always true, this setting can be removed.",
    )
    useContainerOptimizedOs: Optional[bool] = Field(
        None,
        description='If true, use Container-Optimized OS (https://cloud.google.com/container-optimized-os/) base image for VMs, rather than a base Debian image.',
    )


class FileInfo(BaseModel):
    mimeType: Optional[str] = Field(
        None,
        description='The MIME type of the file.Defaults to the value from Google Cloud Storage.',
    )
    sha1Sum: Optional[str] = Field(
        None, description='The SHA1 hash of the file, in hex.'
    )
    sourceUrl: Optional[str] = Field(
        None,
        description="URL source to use to fetch this file. Must be a URL to a resource in Google Cloud Storage in the form 'http(s)://storage.googleapis.com//'.",
    )


class Action(Enum):
    UNSPECIFIED_ACTION = 'UNSPECIFIED_ACTION'
    ALLOW = 'ALLOW'
    DENY = 'DENY'


class FirewallRule(BaseModel):
    action: Optional[Action] = Field(
        None, description='The action to take on matched requests.'
    )
    description: Optional[str] = Field(
        None,
        description='An optional string description of this rule. This field has a maximum length of 400 characters.',
    )
    priority: Optional[int] = Field(
        None,
        description='A positive integer between 1, Int32.MaxValue-1 that defines the order of rule evaluation. Rules with the lowest priority are evaluated first.A default rule at priority Int32.MaxValue matches all IPv4 and IPv6 traffic when no previous rule matches. Only the action of this rule can be modified by the user.',
    )
    sourceRange: Optional[str] = Field(
        None,
        description='IP address or range, defined using CIDR notation, of requests that this rule applies to. You can use the wildcard character "*" to match all IPs equivalent to "0/0" and "::/0" together. Examples: 192.168.1.1 or 192.168.0.0/16 or 2001:db8::/32 or 2001:0db8:0000:0042:0000:8a2e:0370:7334. Truncation will be silently performed on addresses which are not properly truncated. For example, 1.2.3.4/24 is accepted as the same address as 1.2.3.0/24. Similarly, for IPv6, 2001:db8::1/32 is accepted as the same address as 2001:db8::/32.',
    )


class FlexibleRuntimeSettings(BaseModel):
    operatingSystem: Optional[str] = Field(
        None, description='The operating system of the application runtime.'
    )
    runtimeVersion: Optional[str] = Field(
        None, description='The runtime version of an App Engine flexible application.'
    )


class GoogleAppengineV1betaLocationMetadata(BaseModel):
    flexibleEnvironmentAvailable: Optional[bool] = Field(
        None,
        description='App Engine flexible environment is available in the given location.@OutputOnly',
    )
    searchApiAvailable: Optional[bool] = Field(
        None,
        description='Output only. Search API (https://cloud.google.com/appengine/docs/standard/python/search) is available in the given location.',
    )
    standardEnvironmentAvailable: Optional[bool] = Field(
        None,
        description='App Engine standard environment is available in the given location.@OutputOnly',
    )


class HealthCheck(BaseModel):
    checkInterval: Optional[str] = Field(
        None, description='Interval between health checks.'
    )
    disableHealthCheck: Optional[bool] = Field(
        None,
        description='Whether to explicitly disable health checks for this instance.',
    )
    healthyThreshold: Optional[int] = Field(
        None,
        description='Number of consecutive successful health checks required before receiving traffic.',
    )
    host: Optional[str] = Field(
        None,
        description='Host header to send when performing an HTTP health check. Example: "myapp.appspot.com"',
    )
    restartThreshold: Optional[int] = Field(
        None,
        description='Number of consecutive failed health checks required before an instance is restarted.',
    )
    timeout: Optional[str] = Field(
        None, description='Time before the health check is considered failed.'
    )
    unhealthyThreshold: Optional[int] = Field(
        None,
        description='Number of consecutive failed health checks required before removing traffic.',
    )


class IdentityAwareProxy(BaseModel):
    enabled: Optional[bool] = Field(
        None,
        description='Whether the serving infrastructure will authenticate and authorize all incoming requests.If true, the oauth2_client_id and oauth2_client_secret fields must be non-empty.',
    )
    oauth2ClientId: Optional[str] = Field(
        None, description='OAuth2 client ID to use for the authentication flow.'
    )
    oauth2ClientSecret: Optional[str] = Field(
        None,
        description='OAuth2 client secret to use for the authentication flow.For security reasons, this value cannot be retrieved via the API. Instead, the SHA-256 hash of the value is returned in the oauth2_client_secret_sha256 field.@InputOnly',
    )
    oauth2ClientSecretSha256: Optional[str] = Field(
        None,
        description='Output only. Hex-encoded SHA-256 hash of the client secret.@OutputOnly',
    )


class Availability(Enum):
    UNSPECIFIED = 'UNSPECIFIED'
    RESIDENT = 'RESIDENT'
    DYNAMIC = 'DYNAMIC'


class VmLiveness(Enum):
    LIVENESS_STATE_UNSPECIFIED = 'LIVENESS_STATE_UNSPECIFIED'
    UNKNOWN = 'UNKNOWN'
    HEALTHY = 'HEALTHY'
    UNHEALTHY = 'UNHEALTHY'
    DRAINING = 'DRAINING'
    TIMEOUT = 'TIMEOUT'


class Instance(BaseModel):
    appEngineRelease: Optional[str] = Field(
        None, description='Output only. App Engine release this instance is running on.'
    )
    availability: Optional[Availability] = Field(
        None, description='Output only. Availability of the instance.'
    )
    averageLatency: Optional[int] = Field(
        None, description='Output only. Average latency (ms) over the last minute.'
    )
    errors: Optional[int] = Field(
        None,
        description='Output only. Number of errors since this instance was started.',
    )
    id: Optional[str] = Field(
        None,
        description='Output only. Relative name of the instance within the version. Example: instance-1.',
    )
    memoryUsage: Optional[str] = Field(
        None, description='Output only. Total memory in use (bytes).'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Full path to the Instance resource in the API. Example: apps/myapp/services/default/versions/v1/instances/instance-1.',
    )
    qps: Optional[float] = Field(
        None,
        description='Output only. Average queries per second (QPS) over the last minute.',
    )
    requests: Optional[int] = Field(
        None,
        description='Output only. Number of requests since this instance was started.',
    )
    startTime: Optional[str] = Field(
        None, description='Output only. Time that this instance was started.@OutputOnly'
    )
    vmDebugEnabled: Optional[bool] = Field(
        None,
        description='Output only. Whether this instance is in debug mode. Only applicable for instances in App Engine flexible environment.',
    )
    vmId: Optional[str] = Field(
        None,
        description='Output only. Virtual machine ID of this instance. Only applicable for instances in App Engine flexible environment.',
    )
    vmIp: Optional[str] = Field(
        None,
        description='Output only. The IP address of this instance. Only applicable for instances in App Engine flexible environment.',
    )
    vmLiveness: Optional[VmLiveness] = Field(
        None,
        description='Output only. The liveness health check of this instance. Only applicable for instances in App Engine flexible environment.',
    )
    vmName: Optional[str] = Field(
        None,
        description='Output only. Name of the virtual machine where this instance lives. Only applicable for instances in App Engine flexible environment.',
    )
    vmStatus: Optional[str] = Field(
        None,
        description='Output only. Status of the virtual machine where this instance lives. Only applicable for instances in App Engine flexible environment.',
    )
    vmZoneName: Optional[str] = Field(
        None,
        description='Output only. Zone where the virtual machine is located. Only applicable for instances in App Engine flexible environment.',
    )


class Library(BaseModel):
    name: Optional[str] = Field(
        None, description='Name of the library. Example: "django".'
    )
    version: Optional[str] = Field(
        None, description='Version of the library to select, or "latest".'
    )


class ListAuthorizedDomainsResponse(BaseModel):
    domains: Optional[List[AuthorizedDomain]] = Field(
        None, description='The authorized domains belonging to the user.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListIngressRulesResponse(BaseModel):
    ingressRules: Optional[List[FirewallRule]] = Field(
        None, description='The ingress FirewallRules for this application.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListInstancesResponse(BaseModel):
    instances: Optional[List[Instance]] = Field(
        None, description='The instances belonging to the requested version.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class LivenessCheck(BaseModel):
    checkInterval: Optional[str] = Field(
        None, description='Interval between health checks.'
    )
    failureThreshold: Optional[int] = Field(
        None,
        description='Number of consecutive failed checks required before considering the VM unhealthy.',
    )
    host: Optional[str] = Field(
        None,
        description='Host header to send when performing a HTTP Liveness check. Example: "myapp.appspot.com"',
    )
    initialDelay: Optional[str] = Field(
        None, description='The initial delay before starting to execute the checks.'
    )
    path: Optional[str] = Field(None, description='The request path.')
    successThreshold: Optional[int] = Field(
        None,
        description='Number of consecutive successful checks required before considering the VM healthy.',
    )
    timeout: Optional[str] = Field(
        None, description='Time before the check is considered failed.'
    )


class Location(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The friendly name for this location, typically a nearby city name. For example, "Tokyo".',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Cross-service attributes for the location. For example {"cloud.googleapis.com/region": "us-east1"} ',
    )
    locationId: Optional[str] = Field(
        None, description='The canonical id for this location. For example: "us-east1".'
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata. For example the available capacity at the given location.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name for the location, which may vary between implementations. For example: "projects/example-project/locations/us-east1"',
    )


class LocationMetadata(BaseModel):
    flexibleEnvironmentAvailable: Optional[bool] = Field(
        None,
        description='App Engine flexible environment is available in the given location.@OutputOnly',
    )
    searchApiAvailable: Optional[bool] = Field(
        None,
        description='Output only. Search API (https://cloud.google.com/appengine/docs/standard/python/search) is available in the given location.',
    )
    standardEnvironmentAvailable: Optional[bool] = Field(
        None,
        description='App Engine standard environment is available in the given location.@OutputOnly',
    )


class Status(Enum):
    MANAGEMENT_STATUS_UNSPECIFIED = 'MANAGEMENT_STATUS_UNSPECIFIED'
    OK = 'OK'
    PENDING = 'PENDING'
    FAILED_RETRYING_NOT_VISIBLE = 'FAILED_RETRYING_NOT_VISIBLE'
    FAILED_PERMANENT = 'FAILED_PERMANENT'
    FAILED_RETRYING_CAA_FORBIDDEN = 'FAILED_RETRYING_CAA_FORBIDDEN'
    FAILED_RETRYING_CAA_CHECKING = 'FAILED_RETRYING_CAA_CHECKING'


class ManagedCertificate(BaseModel):
    lastRenewalTime: Optional[str] = Field(
        None,
        description='Time at which the certificate was last renewed. The renewal process is fully managed. Certificate renewal will automatically occur before the certificate expires. Renewal errors can be tracked via ManagementStatus.@OutputOnly',
    )
    status: Optional[Status] = Field(
        None,
        description='Status of certificate management. Refers to the most recent certificate acquisition or renewal attempt.@OutputOnly',
    )


class ManualScaling(BaseModel):
    instances: Optional[int] = Field(
        None,
        description='Number of instances to assign to the service at the start. This number can later be altered by using the Modules API (https://cloud.google.com/appengine/docs/python/modules/functions) set_num_instances() function.',
    )


class InstanceIpMode(Enum):
    INSTANCE_IP_MODE_UNSPECIFIED = 'INSTANCE_IP_MODE_UNSPECIFIED'
    EXTERNAL = 'EXTERNAL'
    INTERNAL = 'INTERNAL'


class Network(BaseModel):
    forwardedPorts: Optional[List[str]] = Field(
        None,
        description='List of ports, or port pairs, to forward from the virtual machine to the application container. Only applicable in the App Engine flexible environment.',
    )
    instanceIpMode: Optional[InstanceIpMode] = Field(
        None,
        description='The IP mode for instances. Only applicable in the App Engine flexible environment.',
    )
    instanceTag: Optional[str] = Field(
        None,
        description='Tag to apply to the instance during creation. Only applicable in the App Engine flexible environment.',
    )
    name: Optional[str] = Field(
        None,
        description='Google Compute Engine network where the virtual machines are created. Specify the short name, not the resource path.Defaults to default.',
    )
    sessionAffinity: Optional[bool] = Field(
        None,
        description='Enable session affinity. Only applicable in the App Engine flexible environment.',
    )
    subnetworkName: Optional[str] = Field(
        None,
        description='Google Cloud Platform sub-network where the virtual machines are created. Specify the short name, not the resource path.If a subnetwork name is specified, a network name will also be required unless it is for the default network. If the network that the instance is being created in is a Legacy network, then the IP address is allocated from the IPv4Range. If the network that the instance is being created in is an auto Subnet Mode Network, then only network name should be specified (not the subnetwork_name) and the IP address is created from the IPCidrRange of the subnetwork that exists in that zone for that network. If the network that the instance is being created in is a custom Subnet Mode Network, then the subnetwork_name must be specified and the IP address is created from the IPCidrRange of the subnetwork.If specified, the subnetwork must exist in the same region as the App Engine flexible environment application.',
    )


class IngressTrafficAllowed(Enum):
    INGRESS_TRAFFIC_ALLOWED_UNSPECIFIED = 'INGRESS_TRAFFIC_ALLOWED_UNSPECIFIED'
    INGRESS_TRAFFIC_ALLOWED_ALL = 'INGRESS_TRAFFIC_ALLOWED_ALL'
    INGRESS_TRAFFIC_ALLOWED_INTERNAL_ONLY = 'INGRESS_TRAFFIC_ALLOWED_INTERNAL_ONLY'
    INGRESS_TRAFFIC_ALLOWED_INTERNAL_AND_LB = 'INGRESS_TRAFFIC_ALLOWED_INTERNAL_AND_LB'


class NetworkSettings(BaseModel):
    ingressTrafficAllowed: Optional[IngressTrafficAllowed] = Field(
        None, description='The ingress settings for version or service.'
    )


class NetworkUtilization(BaseModel):
    targetReceivedBytesPerSecond: Optional[int] = Field(
        None, description='Target bytes received per second.'
    )
    targetReceivedPacketsPerSecond: Optional[int] = Field(
        None, description='Target packets received per second.'
    )
    targetSentBytesPerSecond: Optional[int] = Field(
        None, description='Target bytes sent per second.'
    )
    targetSentPacketsPerSecond: Optional[int] = Field(
        None, description='Target packets sent per second.'
    )


class OperationMetadataV1(BaseModel):
    createVersionMetadata: Optional[CreateVersionMetadataV1] = None
    endTime: Optional[str] = Field(
        None, description='Time that this operation completed.@OutputOnly'
    )
    ephemeralMessage: Optional[str] = Field(
        None,
        description='Ephemeral message that may change every time the operation is polled. @OutputOnly',
    )
    insertTime: Optional[str] = Field(
        None, description='Time that this operation was created.@OutputOnly'
    )
    method: Optional[str] = Field(
        None,
        description='API method that initiated this operation. Example: google.appengine.v1.Versions.CreateVersion.@OutputOnly',
    )
    target: Optional[str] = Field(
        None,
        description='Name of the resource that this operation is acting on. Example: apps/myapp/services/default.@OutputOnly',
    )
    user: Optional[str] = Field(
        None, description='User who requested this operation.@OutputOnly'
    )
    warning: Optional[List[str]] = Field(
        None,
        description='Durable messages that persist on every operation poll. @OutputOnly',
    )


class OperationMetadataV1Alpha(BaseModel):
    createVersionMetadata: Optional[CreateVersionMetadataV1Alpha] = None
    endTime: Optional[str] = Field(
        None, description='Time that this operation completed.@OutputOnly'
    )
    ephemeralMessage: Optional[str] = Field(
        None,
        description='Ephemeral message that may change every time the operation is polled. @OutputOnly',
    )
    insertTime: Optional[str] = Field(
        None, description='Time that this operation was created.@OutputOnly'
    )
    method: Optional[str] = Field(
        None,
        description='API method that initiated this operation. Example: google.appengine.v1alpha.Versions.CreateVersion.@OutputOnly',
    )
    target: Optional[str] = Field(
        None,
        description='Name of the resource that this operation is acting on. Example: apps/myapp/services/default.@OutputOnly',
    )
    user: Optional[str] = Field(
        None, description='User who requested this operation.@OutputOnly'
    )
    warning: Optional[List[str]] = Field(
        None,
        description='Durable messages that persist on every operation poll. @OutputOnly',
    )


class OperationMetadataV1Beta(BaseModel):
    createVersionMetadata: Optional[CreateVersionMetadataV1Beta] = None
    endTime: Optional[str] = Field(
        None, description='Time that this operation completed.@OutputOnly'
    )
    ephemeralMessage: Optional[str] = Field(
        None,
        description='Ephemeral message that may change every time the operation is polled. @OutputOnly',
    )
    insertTime: Optional[str] = Field(
        None, description='Time that this operation was created.@OutputOnly'
    )
    method: Optional[str] = Field(
        None,
        description='API method that initiated this operation. Example: google.appengine.v1beta.Versions.CreateVersion.@OutputOnly',
    )
    target: Optional[str] = Field(
        None,
        description='Name of the resource that this operation is acting on. Example: apps/myapp/services/default.@OutputOnly',
    )
    user: Optional[str] = Field(
        None, description='User who requested this operation.@OutputOnly'
    )
    warning: Optional[List[str]] = Field(
        None,
        description='Durable messages that persist on every operation poll. @OutputOnly',
    )


class Phase(Enum):
    UNKNOWN = 'UNKNOWN'
    BEFORE_RESOURCE_HANDLING = 'BEFORE_RESOURCE_HANDLING'
    AFTER_RESOURCE_HANDLING = 'AFTER_RESOURCE_HANDLING'


class State(Enum):
    UNKNOWN_STATE = 'UNKNOWN_STATE'
    ON = 'ON'
    OFF = 'OFF'
    DELETED = 'DELETED'


class ConsumerProjectState(Enum):
    UNKNOWN_STATE = 'UNKNOWN_STATE'
    ON = 'ON'
    OFF = 'OFF'
    DELETED = 'DELETED'


class ProjectsMetadata(BaseModel):
    consumerProjectId: Optional[str] = Field(
        None, description='The consumer project id.'
    )
    consumerProjectNumber: Optional[str] = Field(
        None, description='The consumer project number.'
    )
    consumerProjectState: Optional[ConsumerProjectState] = Field(
        None,
        description='The CCFE state of the consumer project. It is the same state that is communicated to the CLH during project events. Notice that this field is not set in the DB, it is only set in this proto when communicated to CLH in the side channel.',
    )
    p4ServiceAccount: Optional[str] = Field(
        None,
        description='The service account authorized to operate on the consumer project. Note: CCFE only propagates P4SA with default tag to CLH.',
    )
    producerProjectId: Optional[str] = Field(
        None, description='The producer project id.'
    )
    producerProjectNumber: Optional[str] = Field(
        None, description='The producer project number.'
    )
    tenantProjectId: Optional[str] = Field(None, description='The tenant project id.')
    tenantProjectNumber: Optional[str] = Field(
        None, description='The tenant project number.'
    )


class ReadinessCheck(BaseModel):
    appStartTimeout: Optional[str] = Field(
        None,
        description='A maximum time limit on application initialization, measured from moment the application successfully replies to a healthcheck until it is ready to serve traffic.',
    )
    checkInterval: Optional[str] = Field(
        None, description='Interval between health checks.'
    )
    failureThreshold: Optional[int] = Field(
        None,
        description='Number of consecutive failed checks required before removing traffic.',
    )
    host: Optional[str] = Field(
        None,
        description='Host header to send when performing a HTTP Readiness check. Example: "myapp.appspot.com"',
    )
    path: Optional[str] = Field(None, description='The request path.')
    successThreshold: Optional[int] = Field(
        None,
        description='Number of consecutive successful checks required before receiving traffic.',
    )
    timeout: Optional[str] = Field(
        None, description='Time before the check is considered failed.'
    )


class Abuse(Enum):
    ABUSE_UNKNOWN_REASON = 'ABUSE_UNKNOWN_REASON'
    ABUSE_CONTROL_PLANE_SYNC = 'ABUSE_CONTROL_PLANE_SYNC'
    SUSPEND = 'SUSPEND'
    REINSTATE = 'REINSTATE'


class Billing(Enum):
    BILLING_UNKNOWN_REASON = 'BILLING_UNKNOWN_REASON'
    BILLING_CONTROL_PLANE_SYNC = 'BILLING_CONTROL_PLANE_SYNC'
    PROBATION = 'PROBATION'
    CLOSE = 'CLOSE'
    OPEN = 'OPEN'


class DataGovernance(Enum):
    DATA_GOVERNANCE_UNKNOWN_REASON = 'DATA_GOVERNANCE_UNKNOWN_REASON'
    DATA_GOVERNANCE_CONTROL_PLANE_SYNC = 'DATA_GOVERNANCE_CONTROL_PLANE_SYNC'
    HIDE = 'HIDE'
    UNHIDE = 'UNHIDE'
    PURGE = 'PURGE'


class ServiceManagement(Enum):
    SERVICE_MANAGEMENT_UNKNOWN_REASON = 'SERVICE_MANAGEMENT_UNKNOWN_REASON'
    SERVICE_MANAGEMENT_CONTROL_PLANE_SYNC = 'SERVICE_MANAGEMENT_CONTROL_PLANE_SYNC'
    ACTIVATION = 'ACTIVATION'
    PREPARE_DEACTIVATION = 'PREPARE_DEACTIVATION'
    ABORT_DEACTIVATION = 'ABORT_DEACTIVATION'
    COMMIT_DEACTIVATION = 'COMMIT_DEACTIVATION'


class Reasons(BaseModel):
    abuse: Optional[Abuse] = None
    billing: Optional[Billing] = None
    dataGovernance: Optional[DataGovernance] = None
    serviceManagement: Optional[ServiceManagement] = None


class RepairApplicationRequest(BaseModel):
    pass


class RequestUtilization(BaseModel):
    targetConcurrentRequests: Optional[int] = Field(
        None, description='Target number of concurrent requests.'
    )
    targetRequestCountPerSecond: Optional[int] = Field(
        None, description='Target requests per second.'
    )


class Type(Enum):
    A = 'A'
    AAAA = 'AAAA'
    CNAME = 'CNAME'


class ResourceRecord(BaseModel):
    name: Optional[str] = Field(
        None,
        description="Relative name of the object affected by this record. Only applicable for CNAME records. Example: 'www'.",
    )
    rrdata: Optional[str] = Field(
        None,
        description='Data for this record. Values vary by record type, as defined in RFC 1035 (section 5) and RFC 1034 (section 3.6.1).',
    )
    type: Optional[Type] = Field(
        None, description='Resource record type. Example: AAAA.'
    )


class ScriptHandler(BaseModel):
    scriptPath: Optional[str] = Field(
        None, description='Path to the script from the application root directory.'
    )


class SslManagementType(Enum):
    AUTOMATIC = 'AUTOMATIC'
    MANUAL = 'MANUAL'


class SslSettings(BaseModel):
    certificateId: Optional[str] = Field(
        None,
        description='ID of the AuthorizedCertificate resource configuring SSL for the application. Clearing this field will remove SSL support.By default, a managed certificate is automatically created for every domain mapping. To omit SSL support or to configure SSL manually, specify SslManagementType.MANUAL on a CREATE or UPDATE request. You must be authorized to administer the AuthorizedCertificate resource to manually map it to a DomainMapping resource. Example: 12345.',
    )
    pendingManagedCertificateId: Optional[str] = Field(
        None,
        description='ID of the managed AuthorizedCertificate resource currently being provisioned, if applicable. Until the new managed certificate has been successfully provisioned, the previous SSL state will be preserved. Once the provisioning process completes, the certificate_id field will reflect the new managed certificate and this field will be left empty. To remove SSL support while there is still a pending managed certificate, clear the certificate_id field with an UpdateDomainMappingRequest.@OutputOnly',
    )
    sslManagementType: Optional[SslManagementType] = Field(
        None,
        description='SSL management type for this domain. If AUTOMATIC, a managed certificate is automatically provisioned. If MANUAL, certificate_id must be manually specified in order to configure SSL for this domain.',
    )


class StandardSchedulerSettings(BaseModel):
    maxInstances: Optional[int] = Field(
        None,
        description='Maximum number of instances to run for this version. Set to zero to disable max_instances configuration.',
    )
    minInstances: Optional[int] = Field(
        None,
        description='Minimum number of instances to run for this version. Set to zero to disable min_instances configuration.',
    )
    targetCpuUtilization: Optional[float] = Field(
        None, description='Target CPU utilization ratio to maintain when scaling.'
    )
    targetThroughputUtilization: Optional[float] = Field(
        None, description='Target throughput utilization ratio to maintain when scaling'
    )


class StaticFilesHandler(BaseModel):
    applicationReadable: Optional[bool] = Field(
        None,
        description='Whether files should also be uploaded as code data. By default, files declared in static file handlers are uploaded as static data and are only served to end users; they cannot be read by the application. If enabled, uploads are charged against both your code and static data storage resource quotas.',
    )
    expiration: Optional[str] = Field(
        None,
        description='Time a static file served by this handler should be cached by web proxies and browsers.',
    )
    httpHeaders: Optional[Dict[str, str]] = Field(
        None, description='HTTP headers to use for all responses from these URLs.'
    )
    mimeType: Optional[str] = Field(
        None,
        description="MIME type used to serve all files served by this handler.Defaults to file-specific MIME types, which are derived from each file's filename extension.",
    )
    path: Optional[str] = Field(
        None,
        description='Path to the static files matched by the URL pattern, from the application root directory. The path can refer to text matched in groupings in the URL pattern.',
    )
    requireMatchingFile: Optional[bool] = Field(
        None,
        description='Whether this handler should match the request if the file referenced by the handler does not exist.',
    )
    uploadPathRegex: Optional[str] = Field(
        None,
        description='Regular expression that matches the file paths for all files that should be referenced by this handler.',
    )


class StatusModel(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class ShardBy(Enum):
    UNSPECIFIED = 'UNSPECIFIED'
    COOKIE = 'COOKIE'
    IP = 'IP'
    RANDOM = 'RANDOM'


class TrafficSplit(BaseModel):
    allocations: Optional[Dict[str, float]] = Field(
        None,
        description='Mapping from version IDs within the service to fractional (0.000, 1] allocations of traffic for that version. Each version can be specified only once, but some versions in the service may not have any traffic allocation. Services that have traffic allocated cannot be deleted until either the service is deleted or their traffic allocation is removed. Allocations must sum to 1. Up to two decimal place precision is supported for IP-based splits and up to three decimal places is supported for cookie-based splits.',
    )
    shardBy: Optional[ShardBy] = Field(
        None,
        description='Mechanism used to determine which version a request is sent to. The traffic selection algorithm will be stable for either type until allocations are changed.',
    )


class UrlDispatchRule(BaseModel):
    domain: Optional[str] = Field(
        None,
        description='Domain name to match against. The wildcard "*" is supported if specified before a period: "*.".Defaults to matching all domains: "*".',
    )
    path: Optional[str] = Field(
        None,
        description='Pathname within the host. Must start with a "/". A single "*" can be included at the end of the path.The sum of the lengths of the domain and path may not exceed 100 characters.',
    )
    service: Optional[str] = Field(
        None,
        description='Resource ID of a service in this application that should serve the matched request. The service must already exist. Example: default.',
    )


class RedirectHttpResponseCode(Enum):
    REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED = 'REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED'
    REDIRECT_HTTP_RESPONSE_CODE_301 = 'REDIRECT_HTTP_RESPONSE_CODE_301'
    REDIRECT_HTTP_RESPONSE_CODE_302 = 'REDIRECT_HTTP_RESPONSE_CODE_302'
    REDIRECT_HTTP_RESPONSE_CODE_303 = 'REDIRECT_HTTP_RESPONSE_CODE_303'
    REDIRECT_HTTP_RESPONSE_CODE_307 = 'REDIRECT_HTTP_RESPONSE_CODE_307'


class UrlMap(BaseModel):
    apiEndpoint: Optional[ApiEndpointHandler] = Field(
        None, description='Uses API Endpoints to handle requests.'
    )
    authFailAction: Optional[AuthFailAction] = Field(
        None,
        description='Action to take when users access resources that require authentication. Defaults to redirect.',
    )
    login: Optional[Login] = Field(
        None,
        description='Level of login required to access this resource. Not supported for Node.js in the App Engine standard environment.',
    )
    redirectHttpResponseCode: Optional[RedirectHttpResponseCode] = Field(
        None,
        description='30x code to use when performing redirects for the secure field. Defaults to 302.',
    )
    script: Optional[ScriptHandler] = Field(
        None,
        description='Executes a script to handle the requests that match this URL pattern. Only the auto value is supported for Node.js in the App Engine standard environment, for example "script": "auto".',
    )
    securityLevel: Optional[SecurityLevel] = Field(
        None, description='Security (HTTPS) enforcement for this URL.'
    )
    staticFiles: Optional[StaticFilesHandler] = Field(
        None,
        description='Returns the contents of a file, such as an image, as the response.',
    )
    urlRegex: Optional[str] = Field(
        None,
        description='URL prefix. Uses regular expression syntax, which means regexp special characters must be escaped, but should not contain groupings. All URLs that begin with this prefix are handled by this handler, using the portion of the URL after the prefix as part of the file path.',
    )


class InboundService(Enum):
    INBOUND_SERVICE_UNSPECIFIED = 'INBOUND_SERVICE_UNSPECIFIED'
    INBOUND_SERVICE_MAIL = 'INBOUND_SERVICE_MAIL'
    INBOUND_SERVICE_MAIL_BOUNCE = 'INBOUND_SERVICE_MAIL_BOUNCE'
    INBOUND_SERVICE_XMPP_ERROR = 'INBOUND_SERVICE_XMPP_ERROR'
    INBOUND_SERVICE_XMPP_MESSAGE = 'INBOUND_SERVICE_XMPP_MESSAGE'
    INBOUND_SERVICE_XMPP_SUBSCRIBE = 'INBOUND_SERVICE_XMPP_SUBSCRIBE'
    INBOUND_SERVICE_XMPP_PRESENCE = 'INBOUND_SERVICE_XMPP_PRESENCE'
    INBOUND_SERVICE_CHANNEL_PRESENCE = 'INBOUND_SERVICE_CHANNEL_PRESENCE'
    INBOUND_SERVICE_WARMUP = 'INBOUND_SERVICE_WARMUP'


class ServingStatus1(Enum):
    SERVING_STATUS_UNSPECIFIED = 'SERVING_STATUS_UNSPECIFIED'
    SERVING = 'SERVING'
    STOPPED = 'STOPPED'


class Volume(BaseModel):
    name: Optional[str] = Field(None, description='Unique name for the volume.')
    sizeGb: Optional[float] = Field(None, description='Volume size in gigabytes.')
    volumeType: Optional[str] = Field(
        None, description="Underlying volume type, e.g. 'tmpfs'."
    )


class EgressSetting(Enum):
    EGRESS_SETTING_UNSPECIFIED = 'EGRESS_SETTING_UNSPECIFIED'
    ALL_TRAFFIC = 'ALL_TRAFFIC'
    PRIVATE_IP_RANGES = 'PRIVATE_IP_RANGES'


class VpcAccessConnector(BaseModel):
    egressSetting: Optional[EgressSetting] = Field(
        None,
        description='The egress setting for the connector, controlling what traffic is diverted through it.',
    )
    name: Optional[str] = Field(
        None,
        description='Full Serverless VPC Access Connector name e.g. /projects/my-project/locations/us-central1/connectors/c1.',
    )


class ZipInfo(BaseModel):
    filesCount: Optional[int] = Field(
        None,
        description='An estimate of the number of files in a zip for a zip deployment. If set, must be greater than or equal to the actual number of files. Used for optimizing performance; if not provided, deployment may be slow.',
    )
    sourceUrl: Optional[str] = Field(
        None,
        description="URL of the zip file to deploy from. Must be a URL to a resource in Google Cloud Storage in the form 'http(s)://storage.googleapis.com//'.",
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class View(Enum):
    BASIC_CERTIFICATE = 'BASIC_CERTIFICATE'
    FULL_CERTIFICATE = 'FULL_CERTIFICATE'


class OverrideStrategy(Enum):
    UNSPECIFIED_DOMAIN_OVERRIDE_STRATEGY = 'UNSPECIFIED_DOMAIN_OVERRIDE_STRATEGY'
    STRICT = 'STRICT'
    OVERRIDE = 'OVERRIDE'


class View4(Enum):
    BASIC = 'BASIC'
    FULL = 'FULL'


class Application(BaseModel):
    authDomain: Optional[str] = Field(
        None,
        description='Google Apps authentication domain that controls which users can access this application.Defaults to open access for any Google Account.',
    )
    codeBucket: Optional[str] = Field(
        None,
        description='Output only. Google Cloud Storage bucket that can be used for storing files associated with this application. This bucket is associated with the application and can be used by the gcloud deployment commands.@OutputOnly',
    )
    databaseType: Optional[DatabaseType] = Field(
        None,
        description='The type of the Cloud Firestore or Cloud Datastore database associated with this application.',
    )
    defaultBucket: Optional[str] = Field(
        None,
        description='Output only. Google Cloud Storage bucket that can be used by this application to store content.@OutputOnly',
    )
    defaultCookieExpiration: Optional[str] = Field(
        None, description='Cookie expiration policy for this application.'
    )
    defaultHostname: Optional[str] = Field(
        None,
        description='Output only. Hostname used to reach this application, as resolved by App Engine.@OutputOnly',
    )
    dispatchRules: Optional[List[UrlDispatchRule]] = Field(
        None,
        description='HTTP path dispatch rules for requests to the application that do not explicitly target a service or version. Rules are order-dependent. Up to 20 dispatch rules can be supported.',
    )
    featureSettings: Optional[FeatureSettings] = Field(
        None, description='The feature specific settings to be used in the application.'
    )
    gcrDomain: Optional[str] = Field(
        None,
        description='Output only. The Google Container Registry domain used for storing managed build docker images for this application.',
    )
    iap: Optional[IdentityAwareProxy] = None
    id: Optional[str] = Field(
        None,
        description='Identifier of the Application resource. This identifier is equivalent to the project ID of the Google Cloud Platform project where you want to deploy your application. Example: myapp.',
    )
    locationId: Optional[str] = Field(
        None,
        description="Location from which this application runs. Application instances run out of the data centers in the specified location, which is also where all of the application's end user content is stored.Defaults to us-central.View the list of supported locations (https://cloud.google.com/appengine/docs/locations).",
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Full path to the Application resource in the API. Example: apps/myapp.@OutputOnly',
    )
    serviceAccount: Optional[str] = Field(
        None,
        description='The service account associated with the application. This is the app-level default identity. If no identity provided during create version, Admin API will fallback to this one.',
    )
    servingStatus: Optional[ServingStatus] = Field(
        None, description='Serving status of this application.'
    )


class AuthorizedCertificate(BaseModel):
    certificateRawData: Optional[CertificateRawData] = Field(
        None,
        description='The SSL certificate serving the AuthorizedCertificate resource. This must be obtained independently from a certificate authority.',
    )
    displayName: Optional[str] = Field(
        None,
        description='The user-specified display name of the certificate. This is not guaranteed to be unique. Example: My Certificate.',
    )
    domainMappingsCount: Optional[int] = Field(
        None,
        description='Aggregate count of the domain mappings with this certificate mapped. This count includes domain mappings on applications for which the user does not have VIEWER permissions.Only returned by GET or LIST requests when specifically requested by the view=FULL_CERTIFICATE option.@OutputOnly',
    )
    domainNames: Optional[List[str]] = Field(
        None,
        description='Topmost applicable domains of this certificate. This certificate applies to these domains and their subdomains. Example: example.com.@OutputOnly',
    )
    expireTime: Optional[str] = Field(
        None,
        description='The time when this certificate expires. To update the renewal time on this certificate, upload an SSL certificate with a different expiration time using AuthorizedCertificates.UpdateAuthorizedCertificate.@OutputOnly',
    )
    id: Optional[str] = Field(
        None,
        description='Relative name of the certificate. This is a unique value autogenerated on AuthorizedCertificate resource creation. Example: 12345.@OutputOnly',
    )
    managedCertificate: Optional[ManagedCertificate] = Field(
        None,
        description='Only applicable if this certificate is managed by App Engine. Managed certificates are tied to the lifecycle of a DomainMapping and cannot be updated or deleted via the AuthorizedCertificates API. If this certificate is manually administered by the user, this field will be empty.@OutputOnly',
    )
    name: Optional[str] = Field(
        None,
        description='Full path to the AuthorizedCertificate resource in the API. Example: apps/myapp/authorizedCertificates/12345.@OutputOnly',
    )
    visibleDomainMappings: Optional[List[str]] = Field(
        None,
        description='The full paths to user visible Domain Mapping resources that have this certificate mapped. Example: apps/myapp/domainMappings/example.com.This may not represent the full list of mapped domain mappings if the user does not have VIEWER permissions on all of the applications that have this certificate mapped. See domain_mappings_count for a complete count.Only returned by GET or LIST requests when specifically requested by the view=FULL_CERTIFICATE option.@OutputOnly',
    )


class AutomaticScaling(BaseModel):
    coolDownPeriod: Optional[str] = Field(
        None,
        description='The time period that the Autoscaler (https://cloud.google.com/compute/docs/autoscaler/) should wait before it starts collecting information from a new instance. This prevents the autoscaler from collecting information when the instance is initializing, during which the collected usage would not be reliable. Only applicable in the App Engine flexible environment.',
    )
    cpuUtilization: Optional[CpuUtilization] = Field(
        None, description='Target scaling by CPU usage.'
    )
    customMetrics: Optional[List[CustomMetric]] = Field(
        None,
        description='Target scaling by user-provided metrics. Only applicable in the App Engine flexible environment.',
    )
    diskUtilization: Optional[DiskUtilization] = Field(
        None, description='Target scaling by disk usage.'
    )
    maxConcurrentRequests: Optional[int] = Field(
        None,
        description='Number of concurrent requests an automatic scaling instance can accept before the scheduler spawns a new instance.Defaults to a runtime-specific value.',
    )
    maxIdleInstances: Optional[int] = Field(
        None,
        description='Maximum number of idle instances that should be maintained for this version.',
    )
    maxPendingLatency: Optional[str] = Field(
        None,
        description='Maximum amount of time that a request should wait in the pending queue before starting a new instance to handle it.',
    )
    maxTotalInstances: Optional[int] = Field(
        None,
        description='Maximum number of instances that should be started to handle requests for this version.',
    )
    minIdleInstances: Optional[int] = Field(
        None,
        description='Minimum number of idle instances that should be maintained for this version. Only applicable for the default version of a service.',
    )
    minPendingLatency: Optional[str] = Field(
        None,
        description='Minimum amount of time a request should wait in the pending queue before starting a new instance to handle it.',
    )
    minTotalInstances: Optional[int] = Field(
        None,
        description='Minimum number of running instances that should be maintained for this version.',
    )
    networkUtilization: Optional[NetworkUtilization] = Field(
        None, description='Target scaling by network usage.'
    )
    requestUtilization: Optional[RequestUtilization] = Field(
        None, description='Target scaling by request utilization.'
    )
    standardSchedulerSettings: Optional[StandardSchedulerSettings] = Field(
        None, description='Scheduler settings for standard environment.'
    )


class BatchUpdateIngressRulesRequest(BaseModel):
    ingressRules: Optional[List[FirewallRule]] = Field(
        None, description='A list of FirewallRules to replace the existing set.'
    )


class BatchUpdateIngressRulesResponse(BaseModel):
    ingressRules: Optional[List[FirewallRule]] = Field(
        None, description='The full list of ingress FirewallRules for this application.'
    )


class Deployment(BaseModel):
    build: Optional[BuildInfo] = Field(
        None,
        description='Google Cloud Build build information. Only applicable for instances running in the App Engine flexible environment.',
    )
    cloudBuildOptions: Optional[CloudBuildOptions] = Field(
        None,
        description='Options for any Google Cloud Build builds created as a part of this deployment.These options will only be used if a new build is created, such as when deploying to the App Engine flexible environment using files or zip.',
    )
    container: Optional[ContainerInfo] = Field(
        None,
        description='The Docker image for the container that runs the version. Only applicable for instances running in the App Engine flexible environment.',
    )
    files: Optional[Dict[str, FileInfo]] = Field(
        None,
        description='Manifest of the files stored in Google Cloud Storage that are included as part of this version. All files must be readable using the credentials supplied with this call.',
    )
    zip: Optional[ZipInfo] = Field(
        None,
        description='The zip file for this deployment, if this is a zip deployment.',
    )


class DomainMapping(BaseModel):
    id: Optional[str] = Field(
        None,
        description='Relative name of the domain serving the application. Example: example.com.',
    )
    name: Optional[str] = Field(
        None,
        description='Full path to the DomainMapping resource in the API. Example: apps/myapp/domainMapping/example.com.@OutputOnly',
    )
    resourceRecords: Optional[List[ResourceRecord]] = Field(
        None,
        description="The resource records required to configure this domain mapping. These records must be added to the domain's DNS configuration in order to serve the application via this domain mapping.@OutputOnly",
    )
    sslSettings: Optional[SslSettings] = Field(
        None,
        description='SSL configuration for this domain. If unconfigured, this domain will not serve with SSL.',
    )


class ListAuthorizedCertificatesResponse(BaseModel):
    certificates: Optional[List[AuthorizedCertificate]] = Field(
        None, description='The SSL certificates the user is authorized to administer.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListDomainMappingsResponse(BaseModel):
    domainMappings: Optional[List[DomainMapping]] = Field(
        None, description='The domain mappings for the application.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListLocationsResponse(BaseModel):
    locations: Optional[List[Location]] = Field(
        None,
        description='A list of locations that matches the specified filter in the request.',
    )
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is false, it means the operation is still in progress. If true, the operation is completed, and either error or response is available.',
    )
    error: Optional[StatusModel] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the name should be a resource name ending with operations/{unique_id}.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as Delete, the response is google.protobuf.Empty. If the original method is standard Get/Create/Update, the response should be the resource. For other methods, the response should have the type XxxResponse, where Xxx is the original method name. For example, if the original method name is TakeSnapshot(), the inferred response type is TakeSnapshotResponse.',
    )


class ProjectState(BaseModel):
    currentReasons: Optional[Reasons] = None
    previousReasons: Optional[Reasons] = Field(
        None,
        description='The previous and current reasons for a project state will be sent for a project event. CLHs that need to know the signal that caused the project event to trigger (edges) as opposed to just knowing the state can act upon differences in the previous and current reasons.Reasons will be provided for every system: service management, data governance, abuse, and billing.If this is a CCFE-triggered event used for reconciliation then the current reasons will be set to their *_CONTROL_PLANE_SYNC state. The previous reasons will contain the last known set of non-unknown non-control_plane_sync reasons for the state.Reasons fields are deprecated. New tenants should only use the state field. If you must know the reason(s) behind a specific state, please consult with CCFE team first (cloud-ccfe-discuss@google.com).',
    )
    state: Optional[State] = Field(
        None,
        description='The current state of the project. This state is the culmination of all of the opinions from external systems that CCFE knows about of the project.',
    )


class Resources(BaseModel):
    cpu: Optional[float] = Field(None, description='Number of CPU cores needed.')
    diskGb: Optional[float] = Field(None, description='Disk size (GB) needed.')
    kmsKeyReference: Optional[str] = Field(
        None,
        description='The name of the encryption key that is stored in Google Cloud KMS. Only should be used by Cloud Composer to encrypt the vm disk',
    )
    memoryGb: Optional[float] = Field(None, description='Memory (GB) needed.')
    volumes: Optional[List[Volume]] = Field(None, description='User specified volumes.')


class Service(BaseModel):
    id: Optional[str] = Field(
        None,
        description='Relative name of the service within the application. Example: default.@OutputOnly',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='A set of labels to apply to this service. Labels are key/value pairs that describe the service and all resources that belong to it (e.g., versions). The labels can be used to search and group resources, and are propagated to the usage and billing reports, enabling fine-grain analysis of costs. An example of using labels is to tag resources belonging to different environments (e.g., "env=prod", "env=qa"). Label keys and values can be no longer than 63 characters and can only contain lowercase letters, numeric characters, underscores, dashes, and international characters. Label keys must start with a lowercase letter or an international character. Each service can have at most 32 labels.',
    )
    name: Optional[str] = Field(
        None,
        description='Full path to the Service resource in the API. Example: apps/myapp/services/default.@OutputOnly',
    )
    networkSettings: Optional[NetworkSettings] = Field(
        None,
        description='Ingress settings for this service. Will apply to all versions.',
    )
    split: Optional[TrafficSplit] = Field(
        None,
        description='Mapping that defines fractional HTTP traffic diversion to different versions within the service.',
    )


class Version(BaseModel):
    apiConfig: Optional[ApiConfigHandler] = Field(
        None,
        description='Serving configuration for Google Cloud Endpoints (https://cloud.google.com/endpoints).Only returned in GET requests if view=FULL is set.',
    )
    appEngineApis: Optional[bool] = Field(
        None,
        description='Allows App Engine second generation runtimes to access the legacy bundled services.',
    )
    automaticScaling: Optional[AutomaticScaling] = Field(
        None,
        description='Automatic scaling is based on request rate, response latencies, and other application metrics. Instances are dynamically created and destroyed as needed in order to handle traffic.',
    )
    basicScaling: Optional[BasicScaling] = Field(
        None,
        description='A service with basic scaling will create an instance when the application receives a request. The instance will be turned down when the app becomes idle. Basic scaling is ideal for work that is intermittent or driven by user activity.',
    )
    betaSettings: Optional[Dict[str, str]] = Field(
        None,
        description='Metadata settings that are supplied to this version to enable beta runtime features.',
    )
    buildEnvVariables: Optional[Dict[str, str]] = Field(
        None,
        description='Environment variables available to the build environment.Only returned in GET requests if view=FULL is set.',
    )
    createTime: Optional[str] = Field(
        None, description='Time that this version was created.@OutputOnly'
    )
    createdBy: Optional[str] = Field(
        None,
        description='Email address of the user who created this version.@OutputOnly',
    )
    defaultExpiration: Optional[str] = Field(
        None,
        description='Duration that static files should be cached by web proxies and browsers. Only applicable if the corresponding StaticFilesHandler (https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1beta/apps.services.versions#StaticFilesHandler) does not specify its own expiration time.Only returned in GET requests if view=FULL is set.',
    )
    deployment: Optional[Deployment] = Field(
        None,
        description='Code and application artifacts that make up this version.Only returned in GET requests if view=FULL is set.',
    )
    diskUsageBytes: Optional[str] = Field(
        None,
        description='Total size in bytes of all the files that are included in this version and currently hosted on the App Engine disk.@OutputOnly',
    )
    endpointsApiService: Optional[EndpointsApiService] = Field(
        None,
        description='Cloud Endpoints configuration.If endpoints_api_service is set, the Cloud Endpoints Extensible Service Proxy will be provided to serve the API implemented by the app.',
    )
    entrypoint: Optional[Entrypoint] = Field(
        None, description='The entrypoint for the application.'
    )
    env: Optional[str] = Field(
        None,
        description='App Engine execution environment for this version.Defaults to standard.',
    )
    envVariables: Optional[Dict[str, str]] = Field(
        None,
        description='Environment variables available to the application.Only returned in GET requests if view=FULL is set.',
    )
    errorHandlers: Optional[List[ErrorHandler]] = Field(
        None,
        description='Custom static error pages. Limited to 10KB per page.Only returned in GET requests if view=FULL is set.',
    )
    flexibleRuntimeSettings: Optional[FlexibleRuntimeSettings] = Field(
        None, description='Settings for App Engine flexible runtimes.'
    )
    handlers: Optional[List[UrlMap]] = Field(
        None,
        description='An ordered list of URL-matching patterns that should be applied to incoming requests. The first matching URL handles the request and other request handlers are not attempted.Only returned in GET requests if view=FULL is set.',
    )
    healthCheck: Optional[HealthCheck] = Field(
        None,
        description='Configures health checking for instances. Unhealthy instances are stopped and replaced with new instances. Only applicable in the App Engine flexible environment.Only returned in GET requests if view=FULL is set.',
    )
    id: Optional[str] = Field(
        None,
        description='Relative name of the version within the service. Example: v1. Version names can contain only lowercase letters, numbers, or hyphens. Reserved names: "default", "latest", and any name with the prefix "ah-".',
    )
    inboundServices: Optional[List[InboundService]] = Field(
        None,
        description='Before an application can receive email or XMPP messages, the application must be configured to enable the service.',
    )
    instanceClass: Optional[str] = Field(
        None,
        description='Instance class that is used to run this version. Valid values are: AutomaticScaling: F1, F2, F4, F4_1G ManualScaling or BasicScaling: B1, B2, B4, B8, B4_1GDefaults to F1 for AutomaticScaling and B1 for ManualScaling or BasicScaling.',
    )
    libraries: Optional[List[Library]] = Field(
        None,
        description='Configuration for third-party Python runtime libraries that are required by the application.Only returned in GET requests if view=FULL is set.',
    )
    livenessCheck: Optional[LivenessCheck] = Field(
        None,
        description='Configures liveness health checking for instances. Unhealthy instances are stopped and replaced with new instancesOnly returned in GET requests if view=FULL is set.',
    )
    manualScaling: Optional[ManualScaling] = Field(
        None,
        description='A service with manual scaling runs continuously, allowing you to perform complex initialization and rely on the state of its memory over time. Manually scaled versions are sometimes referred to as "backends".',
    )
    name: Optional[str] = Field(
        None,
        description='Full path to the Version resource in the API. Example: apps/myapp/services/default/versions/v1.@OutputOnly',
    )
    network: Optional[Network] = Field(
        None,
        description='Extra network settings. Only applicable in the App Engine flexible environment.',
    )
    nobuildFilesRegex: Optional[str] = Field(
        None,
        description='Files that match this pattern will not be built into this version. Only applicable for Go runtimes.Only returned in GET requests if view=FULL is set.',
    )
    readinessCheck: Optional[ReadinessCheck] = Field(
        None,
        description='Configures readiness health checking for instances. Unhealthy instances are not put into the backend traffic rotation.Only returned in GET requests if view=FULL is set.',
    )
    resources: Optional[Resources] = Field(
        None,
        description='Machine resources for this version. Only applicable in the App Engine flexible environment.',
    )
    runtime: Optional[str] = Field(
        None, description='Desired runtime. Example: python27.'
    )
    runtimeApiVersion: Optional[str] = Field(
        None,
        description='The version of the API in the given runtime environment. Please see the app.yaml reference for valid values at https://cloud.google.com/appengine/docs/standard//config/appref',
    )
    runtimeChannel: Optional[str] = Field(
        None,
        description='The channel of the runtime to use. Only available for some runtimes. Defaults to the default channel.',
    )
    runtimeMainExecutablePath: Optional[str] = Field(
        None, description="The path or name of the app's main executable."
    )
    serviceAccount: Optional[str] = Field(
        None,
        description='The identity that the deployed version will run as. Admin API will use the App Engine Appspot service account as default if this field is neither provided in app.yaml file nor through CLI flag.',
    )
    servingStatus: Optional[ServingStatus1] = Field(
        None,
        description='Current serving status of this version. Only the versions with a SERVING status create instances and can be billed.SERVING_STATUS_UNSPECIFIED is an invalid value. Defaults to SERVING.',
    )
    threadsafe: Optional[bool] = Field(
        None,
        description='Whether multiple requests can be dispatched to this version at once.',
    )
    versionUrl: Optional[str] = Field(
        None,
        description='Serving URL for this version. Example: "https://myversion-dot-myservice-dot-myapp.appspot.com"@OutputOnly',
    )
    vm: Optional[bool] = Field(
        None,
        description='Whether to deploy this version in a container on a virtual machine.',
    )
    vpcAccessConnector: Optional[VpcAccessConnector] = Field(
        None, description='Enables VPC connectivity for standard apps.'
    )
    zones: Optional[List[str]] = Field(
        None,
        description='The Google Compute Engine zones that are supported by this version in the App Engine flexible environment. Deprecated.',
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class ListServicesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    services: Optional[List[Service]] = Field(
        None, description='The services belonging to the requested application.'
    )


class ListVersionsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    versions: Optional[List[Version]] = Field(
        None, description='The versions belonging to the requested service.'
    )


class ProjectEvent(BaseModel):
    eventId: Optional[str] = Field(
        None,
        description='The unique ID for this project event. CLHs can use this value to dedup repeated calls. required',
    )
    phase: Optional[Phase] = None
    projectMetadata: Optional[ProjectsMetadata] = Field(
        None, description='The projects metadata for this project. required'
    )
    state: Optional[ProjectState] = Field(
        None, description='The state of the project that led to this event.'
    )
